name: get_async_page
description: A reactive page in GetX from a stream without the need to create a controller.
version: 0.1.0
homepage: https://github.com/MarceloRab/get_stream_page

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter
  connectivity: ">=0.4.9+5 <5.0.0"
  #get_state_manager: ">=3.13.0 <4.0.0"
  get: ">=3.13.2 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
